/**
 * CGo OpenMap - 车站数据库 (city/beijing/data_stations.js)
 */

const stationsData = {
    "CAE1": { type: "dot", x: 993, y: 591, cn: "北新桥", en: "Beixinqiao", align: "left", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 }, hideLabel: true },
    "CAE2": { type: "dot", x: 1056, y: 591, cn: "东直门", en: "Dongzhimen", align: "left", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 }, hideLabel: true },
    "CAE3": { type: "dot", x: 1190, y: 524, cn: "三元桥", en: "Sanyuanqiao", align: "left", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 }, hideLabel: true },
    "CAE4": { type: "dot", x: 1469, y: 309, cn: "三号航站楼", en: "Terminal 3", align: "right", offset: { x: 0, y: 3 }, textScale: { cn: 1, en: 1 } },
    "CAE5": { type: "dot", x: 1380, y: 309, cn: "二号航站楼", en: "Terminal 2", align: "right", offset: { x: 0, y: 3 }, textScale: { cn: 1, en: 1 } },
    "DAE1": { type: "no", x: 620, y: 892, cn: "丽泽商务区", en: "Lize Shangwuqu", align: "bottom-left", offset: { x: 0, y: -1.5 }, textScale: { cn: 1, en: 1 }, hideLabel: true },
    "DAE2": { type: "tsfo", x: 681, y: 961, cn: "草桥", en: "Caoqiao", align: "top-right", offset: { x: 0, y: -0.5 }, textScale: { cn: 1, en: 1 }, hideLabel: true },
    "DAE3": { type: "dot", x: 803, y: 1118, cn: "大兴新城", en: "Daxing Xincheng", align: "right", offset: { x: 5, y: -4 }, textScale: { cn: 1, en: 1 } },
    "DAE4": { type: "dot", x: 872, y: 1225, cn: "大兴机场", en: "Daxing Airport", align: "right", offset: { x: 0, y: 3 }, textScale: { cn: 1, en: 1 } },
    "JX02": { type: "no", x: 816, y: 1244, cn: "永清临空", en: "Yongqing Linkong", align: "top", offset: { x: 0, y: -1 }, textScale: { cn: 1, en: 1 } },
    "JX03": { type: "no", x: 738, y: 1244, cn: "霸州开发区", en: "Bazhou Development Zone", align: "top", offset: { x: 0, y: -1 }, textScale: { cn: 1, en: 0.95 } },
    "JX04": { type: "no", x: 548, y: 1264, cn: "雄安站", en: "Xiongan Rwy. Sta.", align: "top", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 } },
    "JX05": { type: "no", x: 487, y: 1264, cn: "雄州", en: "Xiongzhou", align: "top", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 } },
    "JX06": { type: "no", x: 422, y: 1264, cn: "大学", en: "University", align: "top", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 } },
    "JX07": { type: "no", x: 356, y: 1264, cn: "金融岛", en: "Jinrongdao", align: "top", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 } },
    "JX08": { type: "no", x: 293, y: 1264, cn: "雄安航站楼", en: "Xiongan Terminal", align: "top", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 } },
    "JX09": { type: "no", x: 635, y: 1264, cn: "昝岗", en: "Zangang", align: "right", offset: { x: 0, y: -5 }, textScale: { cn: 1, en: 1 } },
    "M1001": { type: "tsfo", x: 451, y: 460, cn: "巴沟", en: "Bagou", align: "top", offset: { x: 0, y: -0.5 }, textScale: { cn: 1, en: 1 } },
    "M1002": { type: "tsf", x: 492, y: 460, cn: "苏州街", en: "Suzhoujie", align: "top-right", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 } },
    "M1004": { type: "dot", x: 586, y: 460, cn: "知春里", en: "Zhichunli", align: "bottom", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 } },
    "M1005": { type: "tsf", x: 650, y: 460, cn: "知春路", en: "Zhichunlu", align: "bottom-left", offset: { x: 0, y: -1 }, textScale: { cn: 1, en: 1 } },
    "M1006": { type: "tsf", x: 698, y: 460, cn: "西土城", en: "Xitucheng", align: "top-right", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 } },
    "M1007": { type: "tsf", x: 774, y: 460, cn: "牡丹园", en: "Mudanyuan", align: "top", offset: { x: 0, y: -5 }, textScale: { cn: 1, en: 1 } },
    "M1008": { type: "dot", x: 823, y: 460, cn: "健德门", en: "Jiandemen", align: "top", offset: { x: 0, y: -0.5 }, textScale: { cn: 1, en: 1 } },
    "M101": { type: "no", x: 207, y: 608, cn: "福寿岭", en: "Fushouling", align: "left", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 } },
    "M1010": { type: "dot", x: 937, y: 460, cn: "安贞门", en: "Anzhenmen", align: "top", offset: { x: 0, y: -0.5 }, textScale: { cn: 1, en: 1 } },
    "M1012": { type: "tsf", x: 1056, y: 460, cn: "芍药居", en: "Shaoyaoju", align: "bottom-left", offset: { x: 0, y: -2 }, textScale: { cn: 1, en: 1 } },
    "M1013": { type: "tsf", x: 1110, y: 460, cn: "太阳宫", en: "Taiyanggong", align: "top-right", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 } },
    "M1014": { type: "tsf", x: 1177, y: 511, cn: "三元桥", en: "Sanyuanqiao", align: "bottom-left", offset: { x: 0, y: -1 }, textScale: { cn: 1, en: 1 } },
    "M1015": { type: "dot", x: 1177, y: 545, cn: "亮马桥", en: "Liangmaqiao", align: "left", offset: { x: 0, y: 2.5 }, textScale: { cn: 1, en: 1 } },
    "M1016": { type: "dot", x: 1177, y: 574, cn: "农业展览馆", en: "Agricultural<br>Exhibition Center", align: "left", offset: { x: 0, y: -1.5 }, textScale: { cn: 0.95, en: 1 } },
    "M1019": { type: "dot", x: 1177, y: 678, cn: "金台夕照", en: "Jintai Xizhao", align: "bottom-left", offset: { x: 0, y: -2 }, textScale: { cn: 1, en: 1 } },
    "M1022": { type: "dot", x: 1177, y: 845, cn: "劲松", en: "Jingsong", align: "right", offset: { x: 0, y: -3 }, textScale: { cn: 1, en: 1 } },
    "M1023": { type: "dot", x: 1177, y: 874, cn: "潘家园", en: "Panjiayuan", align: "right", offset: { x: 0, y: -5.5 }, textScale: { cn: 1, en: 1 } },
    "M1024": { type: "tsf", x: 1177, y: 911, cn: "十里河", en: "Shilihe", align: "top-right", offset: { x: 0, y: -0.5 }, textScale: { cn: 1, en: 1 } },
    "M1025": { type: "dot", x: 1102, y: 948, cn: "分钟寺", en: "Fenzhongsi", align: "top", offset: { x: 0, y: -1 }, textScale: { cn: 1, en: 1 } },
    "M1026": { type: "dot", x: 1040, y: 948, cn: "成寿寺", en: "Chengshousi", align: "top", offset: { x: 0, y: -0.5 }, textScale: { cn: 1, en: 1 } },
    "M1028": { type: "dot", x: 942, y: 948, cn: "石榴庄", en: "Shiliuzhuang", align: "bottom", offset: { x: 0, y: -1 }, textScale: { cn: 1, en: 1 } },
    "M103": { type: "dot", x: 252, y: 727, cn: "古城", en: "Gucheng", align: "bottom-left", offset: { x: 2, y: -1 }, textScale: { cn: 1, en: 1 } },
    "M1030": { type: "dot", x: 832, y: 948, cn: "角门东", en: "Jiaomendong", align: "top", offset: { x: 0, y: -0.5 }, textScale: { cn: 1, en: 1 } },
    "M1032": { type: "tsf", x: 694, y: 948, cn: "草桥", en: "Caoqiao", align: "top-right", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 } },
    "M1033": { type: "dot", x: 653, y: 948, cn: "纪家庙", en: "Jijiamiao", align: "top", offset: { x: 0, y: -0.5 }, textScale: { cn: 1, en: 1 } },
    "M1034": { type: "tsf", x: 565, y: 948, cn: "首经贸", en: "Capital Univ. of<br>Economics & Business", align: "bottom-right", offset: { x: 0, y: -2 }, textScale: { cn: 1, en: 1 } },
    "M1035": { type: "tsf", x: 510, y: 943, cn: "丰台站", en: "Fengtai Rwy. Sta.", align: "bottom-right", offset: { x: -24, y: 3 }, textScale: { cn: 1, en: 1 } },
    "M1036": { type: "dot", x: 505, y: 911, cn: "泥洼", en: "Niwa", align: "right", offset: { x: 0, y: -7 }, textScale: { cn: 1, en: 1 } },
    "M1037": { type: "tsf", x: 505, y: 874, cn: "西局", en: "Xiju", align: "top-right", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 } },
    "M1039": { type: "dot", x: 505, y: 759, cn: "莲花桥", en: "Lianhuaqiao", align: "left", offset: { x: 0, y: 3 }, textScale: { cn: 1, en: 1 } },
    "M104": { type: "no", x: 288, y: 727, cn: "八角游乐园", en: "Bajiao Amusement Park", align: "top", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 0.95 } },
    "M1041": { type: "dot", x: 460, y: 658, cn: "西钓鱼台", en: "Xidiaoyutai", align: "left", offset: { x: -4, y: 4 }, textScale: { cn: 1, en: 1 } },
    "M1043": { type: "dot", x: 435, y: 572, cn: "车道沟", en: "Chedaogou", align: "right", offset: { x: 0, y: 0.5 }, textScale: { cn: 1, en: 1 } },
    "M1044": { type: "tsf", x: 435, y: 524, cn: "长春桥", en: "Changchunqiao", align: "top-left", offset: { x: -2, y: 2 }, textScale: { cn: 1, en: 1 } },
    "M1045": { type: "dot", x: 435, y: 491, cn: "火器营", en: "Huoqiying", align: "right", offset: { x: 0, y: 3.5 }, textScale: { cn: 1, en: 1 } },
    "M105": { type: "dot", x: 325, y: 727, cn: "八宝山", en: "Babaoshan", align: "bottom", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 } },
    "M106": { type: "dot", x: 362, y: 727, cn: "玉泉路", en: "Yuquanlu", align: "top", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 } },
    "M107": { type: "dot", x: 399, y: 727, cn: "五棵松", en: "Wukesong", align: "bottom", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 } },
    "M108": { type: "dot", x: 436, y: 727, cn: "万寿路", en: "Wanshoulu", align: "top", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 } },
    "M109": { type: "tsf", x: 505, y: 727, cn: "公主坟", en: "Gongzhufen", align: "top-left", offset: { x: 0, y: 0.5 }, textScale: { cn: 1, en: 0.95 } },
    "M110": { type: "tsf", x: 547, y: 727, cn: "军事博物馆", en: "Military Museum", align: "top-right", offset: { x: 0, y: 0.5 }, textScale: { cn: 1, en: 1 } },
    "M1101": { type: "dot", x: 157, y: 622, cn: "模式口", en: "Moshikou", align: "left", offset: { x: 0, y: -0.5 }, textScale: { cn: 1, en: 1 } },
    "M1103": { type: "dot", x: 157, y: 701, cn: "北辛安", en: "Beixin'an", align: "right", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 } },
    "M1104": { type: "dot", x: 157, y: 727, cn: "新首钢", en: "Shougang Park", align: "right", offset: { x: 0, y: -1 }, textScale: { cn: 1, en: 1 } },
    "M111": { type: "tsfo", x: 632, y: 727, cn: "木樨地", en: "Muxidi", align: "bottom-right", offset: { x: -11.5, y: -1 }, textScale: { cn: 0.9, en: 1 } },
    "M112": { type: "dot", x: 661, y: 727, cn: "南礼士路", en: "Nanlishilu", align: "top", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 } },
    "M113": { type: "tsf", x: 702, y: 727, cn: "复兴门", en: "Fuxingmen", align: "bottom-left", offset: { x: 0, y: -1 }, textScale: { cn: 0.9, en: 0.9 } },
    "M114": { type: "tsf", x: 765, y: 727, cn: "西单", en: "Xidan", align: "top-right", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 } },
    "M115": { type: "dot", x: 824, y: 727, cn: "天安门西", en: "Tian'anmenxi", align: "top", offset: { x: 0, y: -0.5 }, textScale: { cn: 1, en: 1 } },
    "M116": { type: "dot", x: 880, y: 727, cn: "天安门东", en: "Tian'anmendong", align: "top", offset: { x: 0, y: -0.5 }, textScale: { cn: 1, en: 1 } },
    "M117": { type: "tsf", x: 920, y: 727, cn: "王府井", en: "Wangfujing", align: "top-right", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 } },
    "M118": { type: "tsf", x: 978, y: 727, cn: "东单", en: "Dongdan", align: "top-right", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 } },
    "M119": { type: "tsf", x: 1041, y: 727, cn: "建国门", en: "Jianguomen", align: "top-right", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 } },
    "M120": { type: "tsf", x: 1110, y: 727, cn: "永安里", en: "Yong'anli", align: "bottom-left", offset: { x: 0, y: -1 }, textScale: { cn: 1, en: 1 } },
    "M1201": { type: "dot", x: 399, y: 572, cn: "四季青桥", en: "Sijiqingqiao", align: "left", offset: { x: 0, y: 0.5 }, textScale: { cn: 1, en: 1 } },
    "M1202": { type: "dot", x: 413, y: 546, cn: "蓝靛厂", en: "Landianchang", align: "top-left", offset: { x: -2, y: 8.5 }, textScale: { cn: 1, en: 1 } },
    "M1204": { type: "tsf", x: 492, y: 511, cn: "苏州桥", en: "Suzhouqiao", align: "top-right", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 } },
    "M1206": { type: "tsfo", x: 636, y: 511, cn: "大钟寺", en: "Dazhongsi", align: "bottom", offset: { x: -9, y: 0 }, textScale: { cn: 1, en: 1 } },
    "M1207": { type: "tsf", x: 698, y: 511, cn: "蓟门桥", en: "Jimenqiao", align: "top-right", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 } },
    "M1208": { type: "tsf", x: 774, y: 511, cn: "北太平庄", en: "Beitaipingzhuang", align: "top-right", offset: { x: 0, y: 0 }, textScale: { cn: 0.95, en: 0.85 } },
    "M1209": { type: "dot", x: 845, y: 511, cn: "马甸桥", en: "Madianqiao", align: "top", offset: { x: 0, y: -0.5 }, textScale: { cn: 1, en: 0.9 } },
    "M121": { type: "tsf", x: 1177, y: 727, cn: "国贸", en: "Guomao", align: "bottom-left", offset: { x: 0, y: -1 }, textScale: { cn: 1, en: 1 } },
    "M1211": { type: "dot", x: 937, y: 511, cn: "安贞桥", en: "Anzhenqiao", align: "top", offset: { x: 0, y: -1 }, textScale: { cn: 1, en: 1 } },
    "M1213": { type: "tsf", x: 1056, y: 511, cn: "光熙门", en: "Guangximen", align: "top-right", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 0.9 } },
    "M1214": { type: "tsf", x: 1110, y: 511, cn: "西坝河", en: "Xibahe", align: "top-right", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 } },
    "M1216": { type: "dot", x: 1215, y: 511, cn: "将台西", en: "Jiangtaixi", align: "top", offset: { x: 0, y: -1 }, textScale: { cn: 1, en: 1 } },
    "M1217": { type: "dot", x: 1252, y: 511, cn: "高家园", en: "Gaojiayuan", align: "top-right", offset: { x: -12, y: 0 }, textScale: { cn: 1, en: 1 } },
    "M1218": { type: "dot", x: 1309.1, y: 511, cn: "驼房营", en: "Tuofangying", align: "top", offset: { x: 0, y: -1 }, textScale: { cn: 1, en: 1 } },
    "M1219": { type: "dot", x: 1355, y: 511, cn: "东坝西", en: "Dongbaxi", align: "top", offset: { x: 0, y: -1 }, textScale: { cn: 1, en: 1 } },
    "M122": { type: "tsf", x: 1240, y: 727, cn: "大望路", en: "Dawanglu", align: "bottom-left", offset: { x: 0, y: -1 }, textScale: { cn: 1, en: 1 } },
    "M123": { type: "dot", x: 1296, y: 727, cn: "四惠", en: "Sihui", align: "top", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 } },
    "M124": { type: "dot", x: 1338, y: 727, cn: "四惠东", en: "Sihuidong", align: "bottom", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 } },
    "M125": { type: "dot", x: 1382, y: 727, cn: "高碑店", en: "Gaobeidian", align: "bottom", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 } },
    "M126": { type: "dot", x: 1430, y: 727, cn: "传媒大学", en: "Communication<br>Univ. of China", align: "bottom", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 } },
    "M127": { type: "dot", x: 1476, y: 727, cn: "双桥", en: "Shuangqiao", align: "bottom", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 0.95 } },
    "M128": { type: "dot", x: 1517, y: 727, cn: "管庄", en: "Guaanzhuang", align: "bottom", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 0.95 } },
    "M129": { type: "dot", x: 1548, y: 730, cn: "八里桥", en: "Baliqiao", align: "top-right", offset: { x: -6, y: -1 }, textScale: { cn: 1, en: 1 } },
    "M130": { type: "dot", x: 1578, y: 760, cn: "通州北苑", en: "Tongzhou Beiyuan", align: "right", offset: { x: 5, y: -4.5 }, textScale: { cn: 1, en: 1 } },
    "M1302": { type: "tsfo", x: 650, y: 511, cn: "大钟寺", en: "Dazhongsi", align: "top-left", offset: { x: 10, y: -1 }, textScale: { cn: 1, en: 1 }, hideLabel: true },
    "M1304": { type: "dot", x: 650, y: 408, cn: "五道口", en: "Wudaokou", align: "left", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 } },
    "M1305": { type: "dot", x: 650, y: 340, cn: "上地", en: "Shangdi", align: "left", offset: { x: 0, y: -2 }, textScale: { cn: 1, en: 1 } },
    "M1306": { type: "tsf", x: 646, y: 316, cn: "清河站", en: "Qinghe Rwy. Sta.", align: "left", offset: { x: -5, y: -4 }, textScale: { cn: 1, en: 1 } },
    "M1307": { type: "tsf", x: 646, y: 285, cn: "西二旗", en: "Xi'erqi", align: "left", offset: { x: -5, y: 1.5 }, textScale: { cn: 1, en: 1 } },
    "M1308": { type: "dot", x: 788, y: 270, cn: "龙泽", en: "Longze", align: "top", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 } },
    "M1309": { type: "dot", x: 841, y: 270, cn: "回龙观", en: "Huilongguan", align: "top", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 } },
    "M131": { type: "dot", x: 1606.5, y: 788.5, cn: "果园", en: "Guoyuan", align: "bottom-left", offset: { x: -4, y: -12 }, textScale: { cn: 1, en: 1 } },
    "M1312": { type: "dot", x: 1045, y: 296, cn: "北苑", en: "Beiyuan", align: "top", offset: { x: 0, y: -0.5 }, textScale: { cn: 1, en: 1 } },
    "M1313": { type: "tsf", x: 1083, y: 380, cn: "望京西", en: "Wangjingxi", align: "top-right", offset: { x: 4, y: 0 }, textScale: { cn: 1, en: 1 } },
    "M1316": { type: "dot", x: 1056, y: 533, cn: "柳芳", en: "Liufang", align: "right", offset: { x: 0, y: -1.5 }, textScale: { cn: 1, en: 1 } },
    "M1317": { type: "no", x: 671, y: 538, cn: "四道口", en: "Sidaokou", align: "bottom-left", offset: { x: 1, y: -4 }, textScale: { cn: 1, en: 1 } },
    "M1318": { type: "no", x: 650, y: 432, cn: "保福寺", en: "Baofusi", align: "left", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 } },
    "M1319": { type: "no", x: 937, y: 270, cn: "东小口", en: "Dongxiaokou", align: "bottom", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 } },
    "M132": { type: "dot", x: 1627.5, y: 809.5, cn: "九棵树", en: "Jiukeshu", align: "bottom-left", offset: { x: -1, y: -10 }, textScale: { cn: 1, en: 1 } },
    "M133": { type: "dot", x: 1648.5, y: 830.5, cn: "梨园", en: "Liyuan", align: "bottom-left", offset: { x: -3, y: -9 }, textScale: { cn: 1, en: 1 } },
    "M134": { type: "dot", x: 1669.5, y: 851.5, cn: "临河里", en: "Linheli", align: "bottom-left", offset: { x: 1, y: -5 }, textScale: { cn: 1, en: 1 } },
    "M135": { type: "dot", x: 1685, y: 897, cn: "土桥", en: "Tuqiao", align: "right", offset: { x: 0, y: -2 }, textScale: { cn: 1, en: 1 } },
    "M136": { type: "tsf", x: 1681, y: 935, cn: "花庄", en: "Huazhuang", align: "right", offset: { x: 3.5, y: -6 }, textScale: { cn: 1, en: 1 } },
    "M137": { type: "tsf", x: 1647, y: 963, cn: "环球度假区", en: "Universal Resort", align: "left", offset: { x: -4.5, y: -1 }, textScale: { cn: 1, en: 1 } },
    "M138": { type: "no", x: 267, y: 759, cn: "衙门口西", en: "Yamenkouxi", align: "right", offset: { x: 0, y: 3 }, textScale: { cn: 1, en: 1 } },
    "M139": { type: "no", x: 267, y: 820, cn: "园博园西", en: "Garden Expo Park West", align: "right", offset: { x: 0, y: 5 }, textScale: { cn: 1, en: 1 } },
    "M140": { type: "no", x: 267, y: 874, cn: "张郭庄", en: "Zhangguozhuang", align: "bottom", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 }, hideLabel: true },
    "M1401": { type: "dot", x: 267, y: 874, cn: "张郭庄", en: "Zhangguozhuang", align: "top-right", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 } },
    "M1402": { type: "dot", x: 332, y: 874, cn: "园博园", en: "Garden<br>Expo Park", align: "bottom", offset: { x: 0, y: -0.5 }, textScale: { cn: 1, en: 1 } },
    "M1403": { type: "dot", x: 359, y: 874, cn: "大瓦窑", en: "Dawayao", align: "top", offset: { x: 0, y: -0.5 }, textScale: { cn: 1, en: 1 } },
    "M1404": { type: "dot", x: 387, y: 874, cn: "郭庄子", en: "Guozhuangzi", align: "bottom", offset: { x: 0, y: -0.5 }, textScale: { cn: 1, en: 1 } },
    "M1405": { type: "dot", x: 414, y: 874, cn: "大井", en: "Dajing", align: "top", offset: { x: 0, y: -0.5 }, textScale: { cn: 1, en: 1 } },
    "M1408": { type: "dot", x: 565, y: 874, cn: "东管头", en: "Dongguantou", align: "top", offset: { x: 0, y: -0.5 }, textScale: { cn: 1, en: 1 } },
    "M1409": { type: "tsf", x: 620, y: 874, cn: "丽泽商务区", en: "Lize Shangwuqu", align: "bottom-left", offset: { x: 0, y: -1.5 }, textScale: { cn: 1, en: 1 } },
    "M141": { type: "no", x: 267, y: 911, cn: "北宫", en: "Beigong", align: "right", offset: { x: 0, y: -7.5 }, textScale: { cn: 1, en: 1 } },
    "M1410": { type: "dot", x: 653, y: 874, cn: "菜户营", en: "Caihuying", align: "bottom", offset: { x: 0, y: -0.5 }, textScale: { cn: 1, en: 1 } },
    "M1411": { type: "dot", x: 681, y: 874, cn: "西铁营", en: "Xitieying", align: "top-right", offset: { x: -14, y: 0 }, textScale: { cn: 1, en: 1 } },
    "M1412": { type: "tsf", x: 716, y: 874, cn: "景风门", en: "Jingfengmen", align: "bottom-right", offset: { x: 0, y: -1.5 }, textScale: { cn: 0.95, en: 0.95 } },
    "M1414": { type: "no", x: 832, y: 874, cn: "陶然桥", en: "Taoranqiao", align: "top", offset: { x: 0, y: -0.5 }, textScale: { cn: 1, en: 1 } },
    "M1416": { type: "dot", x: 942, y: 874, cn: "景泰", en: "Jingtai", align: "bottom", offset: { x: 0, y: -0.5 }, textScale: { cn: 1, en: 1 } },
    "M1418": { type: "dot", x: 1040, y: 874, cn: "方庄", en: "Fangzhuang", align: "top", offset: { x: 0, y: -0.5 }, textScale: { cn: 1, en: 1 } },
    "M142": { type: "no", x: 262, y: 960, cn: "后吕村", en: "Houlyucun", align: "left", offset: { x: -20, y: 10 }, textScale: { cn: 1, en: 1 }, hideLabel: true },
    "M1420": { type: "dot", x: 1240, y: 874, cn: "北工大西门", en: "Beijing Univ. of Tech. West Gate", align: "right", offset: { x: 0, y: -5.5 }, textScale: { cn: 1, en: 0.9 } },
    "M1421": { type: "dot", x: 1240, y: 845, cn: "平乐园", en: "Pingleyuan", align: "right", offset: { x: 0, y: -3 }, textScale: { cn: 1, en: 1 } },
    "M1424": { type: "no", x: 1240, y: 678, cn: "红庙", en: "Hongmiao", align: "bottom-left", offset: { x: 0, y: -2 }, textScale: { cn: 1, en: 1 } },
    "M1427": { type: "dot", x: 1240, y: 581, cn: "枣营", en: "Zaoying", align: "right", offset: { x: 0, y: 2 }, textScale: { cn: 1, en: 1 } },
    "M1428": { type: "dot", x: 1240, y: 557.5, cn: "东风北桥", en: "Dongfeng Beiqiao", align: "right", offset: { x: 0, y: 2 }, textScale: { cn: 1, en: 1 } },
    "M1429": { type: "dot", x: 1240, y: 534, cn: "将台", en: "Jiangtai", align: "right", offset: { x: 0, y: 2 }, textScale: { cn: 1, en: 1 } },
    "M143": { type: "no", x: 203, y: 1011, cn: "云岗", en: "Yungang", align: "bottom", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 } },
    "M1430": { type: "no", x: 1252, y: 511, cn: "高家园", en: "Gaojiayuan", align: "top-right", offset: { x: -8, y: -1 }, textScale: { cn: 1, en: 1 }, hideLabel: true },
    "M1431": { type: "dot", x: 1235, y: 447, cn: "望京南", en: "Wangjingnan", align: "right", offset: { x: 5, y: -2.5 }, textScale: { cn: 1, en: 1 } },
    "M1432": { type: "dot", x: 1201, y: 413, cn: "阜通", en: "Futong", align: "bottom-left", offset: { x: -1, y: -10 }, textScale: { cn: 1, en: 1 } },
    "M1433": { type: "tsf", x: 1177, y: 380, cn: "望京", en: "Wangjing", align: "bottom-left", offset: { x: 0, y: -2 }, textScale: { cn: 1, en: 1 } },
    "M1434": { type: "dot", x: 1177, y: 355, cn: "东湖渠", en: "Donghuqu", align: "right", offset: { x: 0, y: 2 }, textScale: { cn: 1, en: 1 } },
    "M1435": { type: "dot", x: 1177, y: 332, cn: "来广营", en: "Laiguangying", align: "right", offset: { x: 0, y: 2.5 }, textScale: { cn: 1, en: 1 } },
    "M1436": { type: "dot", x: 1177, y: 296, cn: "善各庄", en: "Shangezhuang", align: "top", offset: { x: 0, y: -0.5 }, textScale: { cn: 1, en: 1 } },
    "M144": { type: "no", x: 170, y: 1011, cn: "王佐", en: "Wangzuo", align: "top", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 } },
    "M145": { type: "no", x: 137, y: 1011, cn: "魏各庄", en: "Weigezhuang", align: "bottom", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 } },
    "M146": { type: "no", x: 104, y: 1011, cn: "青龙湖东", en: "Qinglonghudong", align: "top", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 } },
    "M1501": { type: "dot", x: 650, y: 380, cn: "清华东路西口", en: "Qinghua Donglu Xikou", align: "left", offset: { x: 0, y: -15 }, textScale: { cn: 0.9, en: 0.9 } },
    "M1502": { type: "tsf", x: 698, y: 380, cn: "六道口", en: "Liudaokou", align: "bottom-right", offset: { x: 0, y: -1 }, textScale: { cn: 1, en: 1 } },
    "M1503": { type: "dot", x: 774, y: 380, cn: "北沙滩", en: "Beishatan", align: "bottom", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 } },
    "M1505": { type: "dot", x: 937, y: 380, cn: "安立路", en: "Anlilu", align: "top", offset: { x: 0, y: -1 }, textScale: { cn: 1, en: 1 } },
    "M1507": { type: "dot", x: 1045, y: 380, cn: "关庄", en: "Guanzhuang", align: "bottom", offset: { x: 0, y: -1 }, textScale: { cn: 1, en: 1 } },
    "M1510": { type: "dot", x: 1235, y: 380, cn: "望京东", en: "Wangjingdong", align: "bottom", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 } },
    "M1511": { type: "dot", x: 1293, y: 355, cn: "崔各庄", en: "Cuigezhuang", align: "right", offset: { x: 0, y: 2 }, textScale: { cn: 1, en: 1 } },
    "M1512": { type: "dot", x: 1293, y: 332, cn: "马泉营", en: "Maquanying", align: "right", offset: { x: 0, y: 2 }, textScale: { cn: 1, en: 1 } },
    "M1513": { type: "dot", x: 1293, y: 309, cn: "孙河", en: "Sunhe", align: "right", offset: { x: 0, y: 3 }, textScale: { cn: 1, en: 1 } },
    "M1514": { type: "dot", x: 1293, y: 286, cn: "国展", en: "China Int'l<br>Exhibition Center", align: "left", offset: { x: 0, y: -2 }, textScale: { cn: 1, en: 1 } },
    "M1515": { type: "dot", x: 1293, y: 240, cn: "花梨坎", en: "Hualikan", align: "left", offset: { x: 0, y: -5.5 }, textScale: { cn: 1, en: 1 } },
    "M1516": { type: "dot", x: 1293, y: 217, cn: "后沙峪", en: "Houshayu", align: "left", offset: { x: 0, y: -6 }, textScale: { cn: 1, en: 1 } },
    "M1517": { type: "dot", x: 1469, y: 202, cn: "南法信", en: "Nanfaxin", align: "top", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 } },
    "M1518": { type: "dot", x: 1582, y: 202, cn: "石门", en: "Shimen", align: "top", offset: { x: -3, y: 0 }, textScale: { cn: 1, en: 1 } },
    "M1519": { type: "dot", x: 1661, y: 202, cn: "顺义", en: "Shunyi", align: "top", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 } },
    "M1520": { type: "dot", x: 1726, y: 202, cn: "俸伯", en: "Fengbo", align: "bottom", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 } },
    "M1521": { type: "no", x: 1293, y: 263, cn: "国展北", en: "Guozhanbei", align: "left", offset: { x: 0, y: -6 }, textScale: { cn: 1, en: 1 } },
    "M1601": { type: "dot", x: 289, y: 236, cn: "北安河", en: "Bei'anhe", align: "top", offset: { x: 0, y: -0.5 }, textScale: { cn: 1, en: 1 } },
    "M1602": { type: "dot", x: 327, y: 236, cn: "温阳路", en: "Wenyanglu", align: "bottom", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 } },
    "M1603": { type: "dot", x: 366, y: 236, cn: "稻香湖路", en: "Daoxianghulu", align: "top", offset: { x: 0, y: -0.5 }, textScale: { cn: 1, en: 1 } },
    "M1604": { type: "dot", x: 405, y: 236, cn: "屯佃", en: "Tundian", align: "bottom", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 } },
    "M1605": { type: "dot", x: 443, y: 236, cn: "永丰", en: "Yongfeng", align: "top", offset: { x: 0, y: -0.5 }, textScale: { cn: 1, en: 1 } },
    "M1606": { type: "dot", x: 492, y: 260, cn: "永丰南", en: "Yongfengnan", align: "left", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 } },
    "M1607": { type: "dot", x: 492, y: 285, cn: "西北旺", en: "Xibeiwang", align: "left", offset: { x: 0, y: 1 }, textScale: { cn: 1, en: 1 } },
    "M1608": { type: "tsf", x: 492, y: 313, cn: "马连洼", en: "Malianwa", align: "left", offset: { x: -4, y: -0.5 }, textScale: { cn: 1, en: 1 } },
    "M1609": { type: "dot", x: 492, y: 341, cn: "农大南路", en: "Nongda Nanlu", align: "left", offset: { x: 0, y: -3 }, textScale: { cn: 1, en: 1 } },
    "M1611": { type: "dot", x: 492, y: 420, cn: "万泉河桥", en: "Wanquanheqiao", align: "left", offset: { x: 0, y: -1 }, textScale: { cn: 1, en: 1 } },
    "M1614": { type: "dot", x: 492, y: 541, cn: "万寿寺", en: "Wanshousi", align: "left", offset: { x: 0, y: -2.5 }, textScale: { cn: 1, en: 1 } },
    "M1617": { type: "dot", x: 620, y: 658, cn: "甘家口", en: "Ganjiakou", align: "left", offset: { x: 0, y: 4 }, textScale: { cn: 1, en: 1 } },
    "M1618": { type: "dot", x: 620, y: 688, cn: "玉渊潭东门", en: "Yuyuantan Park East Gate", align: "right", offset: { x: 0, y: -2 }, textScale: { cn: 0.95, en: 0.85 } },
    "M1619": { type: "tsfo", x: 620, y: 715, cn: "木樨地", en: "Muxidi", align: "bottom-right", offset: { x: -10, y: -1 }, textScale: { cn: 0.9, en: 1 }, hideLabel: true },
    "M1621": { type: "dot", x: 620, y: 843, cn: "红莲南路", en: "Honglian Nanlu", align: "right", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 0.9 } },
    "M1623": { type: "tsf", x: 565, y: 911, cn: "东管头南", en: "Dongguantounan", align: "bottom-right", offset: { x: 0, y: -2 }, textScale: { cn: 1, en: 1 } },
    "M1626": { type: "dot", x: 414, y: 948, cn: "富丰桥", en: "Fufengqiao", align: "bottom", offset: { x: 0, y: -0.5 }, textScale: { cn: 1, en: 1 } },
    "M1627": { type: "dot", x: 387, y: 948, cn: "看丹", en: "Kandan", align: "top", offset: { x: 0, y: -1 }, textScale: { cn: 1, en: 1 } },
    "M1628": { type: "dot", x: 359, y: 948, cn: "榆树庄", en: "Yushuzhuang", align: "bottom", offset: { x: 0, y: -0.5 }, textScale: { cn: 1, en: 1 } },
    "M1629": { type: "dot", x: 332, y: 948, cn: "洪泰庄", en: "Hongtaizhuang", align: "top", offset: { x: 0, y: -1 }, textScale: { cn: 1, en: 1 } },
    "M1630": { type: "dot", x: 305, y: 948, cn: "宛平城", en: "Wanpingcheng", align: "bottom", offset: { x: 0, y: -0.5 }, textScale: { cn: 1, en: 1 } },
    "M1701": { type: "dot", x: 1079, y: 176, cn: "未来科学城北", en: "Future Science City North", align: "right", offset: { x: 0, y: -3 }, textScale: { cn: 1, en: 1 } },
    "M1702": { type: "dot", x: 1079, y: 199, cn: "未来科学城", en: "Future Science City", align: "right", offset: { x: 0, y: -2 }, textScale: { cn: 1, en: 1 } },
    "M1703": { type: "tsf", x: 1079, y: 237, cn: "天通苑东", en: "Tiantongyuandong", align: "top-right", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 } },
    "M1704": { type: "dot", x: 1079, y: 262, cn: "清河营", en: "Qingheying", align: "right", offset: { x: 0, y: -5.5 }, textScale: { cn: 1, en: 1 } },
    "M1705": { type: "dot", x: 1079, y: 344, cn: "红军营", en: "Hongjunying", align: "left", offset: { x: 0, y: -1 }, textScale: { cn: 1, en: 1 } },
    "M1709": { type: "dot", x: 1110, y: 574, cn: "左家庄", en: "Zuojiazhuang", align: "left", offset: { x: 0, y: -4.5 }, textScale: { cn: 1, en: 0.95 } },
    "M1713": { type: "no", x: 1110, y: 812, cn: "广渠门外", en: "Guangqumenwai", align: "top-left", offset: { x: 8, y: 0 }, textScale: { cn: 1, en: 1 }, hideLabel: true },
    "M1714": { type: "dot", x: 1125, y: 859, cn: "潘家园西", en: "Panjiayuanxi", align: "bottom-left", offset: { x: 0, y: -6 }, textScale: { cn: 1, en: 1 } },
    "M1716": { type: "dot", x: 1223, y: 957, cn: "周家庄", en: "Zhoujiazhuang", align: "top-right", offset: { x: 1, y: 5 }, textScale: { cn: 1, en: 1 } },
    "M1717": { type: "dot", x: 1257, y: 991, cn: "十八里店", en: "Shibalidian", align: "top-right", offset: { x: 0, y: 5 }, textScale: { cn: 1, en: 1 } },
    "M1718": { type: "dot", x: 1290, y: 1024, cn: "北神树", en: "Beishenshu", align: "top-right", offset: { x: -1, y: 4 }, textScale: { cn: 1, en: 1 } },
    "M1719": { type: "dot", x: 1324, y: 1058, cn: "次渠北", en: "Ciqubei", align: "top-right", offset: { x: -1, y: 4 }, textScale: { cn: 1, en: 1 } },
    "M1720": { type: "tsf", x: 1361, y: 1095, cn: "次渠", en: "Ciqu", align: "bottom-left", offset: { x: 0, y: -1 }, textScale: { cn: 1, en: 1 } },
    "M1721": { type: "dot", x: 1424, y: 1133, cn: "嘉会湖", en: "Jiahuihu", align: "top", offset: { x: 0, y: -1 }, textScale: { cn: 1, en: 1 } },
    "M1802": { type: "dot", x: 565, y: 285, cn: "上地软件园", en: "Shangdi<br>Software Park", align: "left", offset: { x: -1, y: 4 }, textScale: { cn: 1, en: 1 } },
    "M1803": { type: "dot", x: 586, y: 262, cn: "东北旺", en: "Dongbeiwang", align: "top", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 } },
    "M1804": { type: "dot", x: 709, y: 262, cn: "龙泽西", en: "Longzexi", align: "top-left", offset: { x: 5, y: 0 }, textScale: { cn: 1, en: 1 } },
    "M1805": { type: "dot", x: 788, y: 237, cn: "回龙观西大街", en: "Huilongguan Xidajie", align: "top", offset: { x: 0, y: 0 }, textScale: { cn: 0.9, en: 0.95 } },
    "M1806": { type: "dot", x: 841, y: 237, cn: "文华路", en: "Wenhualu", align: "top", offset: { x: 0, y: 0 }, textScale: { cn: 0.95, en: 1 } },
    "M1808": { type: "dot", x: 937, y: 237, cn: "霍营东", en: "Huoyingdong", align: "bottom", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 } },
    "M1810": { type: "dot", x: 1045, y: 237, cn: "太平庄", en: "Taipingzhuang", align: "top", offset: { x: 0, y: -1 }, textScale: { cn: 1, en: 0.9 } },
    "M1905": { type: "tsfo", x: 716, y: 713, cn: "太平桥", en: "Taipingqiao", align: "right", offset: { x: 0, y: -2 }, textScale: { cn: 1, en: 0.95 } },
    "M1906": { type: "tsfo", x: 716, y: 800, cn: "牛街", en: "Niujie", align: "right", offset: { x: 0, y: -4 }, textScale: { cn: 1, en: 1 } },
    "M1909": { type: "dot", x: 694, y: 977, cn: "新发地", en: "Xinfadi", align: "right", offset: { x: 0, y: -7.5 }, textScale: { cn: 1, en: 1 } },
    "M201": { type: "tsf", x: 698, y: 588, cn: "西直门", en: "Xizhimen", align: "top-right", offset: { x: 4, y: 0 }, textScale: { cn: 1, en: 1 } },
    "M202": { type: "tsf", x: 774, y: 554, cn: "积水潭", en: "Jishuitan", align: "bottom-right", offset: { x: 0, y: -1 }, textScale: { cn: 1, en: 1 } },
    "M203": { type: "tsf", x: 872, y: 554, cn: "鼓楼大街", en: "Gulou Dajie", align: "bottom-left", offset: { x: 0, y: -1 }, textScale: { cn: 1, en: 1 } },
    "M204": { type: "dot", x: 937, y: 554, cn: "安定门", en: "Andingmen", align: "top", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 } },
    "M205": { type: "tsf", x: 978, y: 554, cn: "雍和宫", en: "Yonghegong Lama Temple", align: "bottom-left", offset: { x: 0, y: -1 }, textScale: { cn: 1, en: 0.95 } },
    "M206": { type: "tsf", x: 1041, y: 576, cn: "东直门", en: "Dongzhimen", align: "left", offset: { x: -4, y: -7 }, textScale: { cn: 1, en: 1 } },
    "M207": { type: "tsf", x: 1041, y: 623, cn: "东四十条", en: "Dongsi Shitiao", align: "left", offset: { x: -3, y: -6.5 }, textScale: { cn: 0.95, en: 0.95 } },
    "M208": { type: "tsf", x: 1041, y: 656, cn: "朝阳门", en: "Chaoyangmen", align: "top-left", offset: { x: 0, y: 1 }, textScale: { cn: 1, en: 1 } },
    "M210": { type: "dot", x: 1040, y: 755, cn: "北京站", en: "Beijing Rwy. Sta.", align: "right", offset: { x: -0.5, y: 7 }, textScale: { cn: 1, en: 1 } },
    "M211": { type: "tsf", x: 978, y: 765, cn: "崇文门", en: "Chongwenmen", align: "top-left", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 } },
    "M212": { type: "tsf", x: 895, y: 765, cn: "前门", en: "Qianmen", align: "top-left", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 } },
    "M213": { type: "dot", x: 824, y: 765, cn: "和平门", en: "Hepingmen", align: "top", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 } },
    "M214": { type: "tsf", x: 765, y: 765, cn: "宣武门", en: "Xuanwumen", align: "top-left", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 } },
    "M215": { type: "dot", x: 705, y: 760, cn: "长椿街", en: "Changchunjie", align: "left", offset: { x: -2, y: 2 }, textScale: { cn: 1, en: 1 } },
    "M217": { type: "dot", x: 702, y: 658, cn: "阜成门", en: "Fuchengmen", align: "left", offset: { x: 0, y: 4 }, textScale: { cn: 1, en: 1 } },
    "M218": { type: "tsf", x: 702, y: 623, cn: "车公庄", en: "Chegongzhuang", align: "bottom-left", offset: { x: 0, y: -1 }, textScale: { cn: 1, en: 1 } },
    "M2204": { type: "no", x: 1296, y: 678, cn: "慈云寺", en: "Ciyunsi", align: "bottom", offset: { x: 0, y: -1 }, textScale: { cn: 1, en: 1 } },
    "M2205": { type: "no", x: 1361, y: 678, cn: "甘露园", en: "Ganluyuan", align: "bottom", offset: { x: 0, y: -1 }, textScale: { cn: 1, en: 1 } },
    "M2206": { type: "no", x: 1430, y: 678, cn: "定福庄", en: "Dingfuzhuang", align: "bottom", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 } },
    "M2207": { type: "no", x: 1509, y: 719, cn: "管庄", en: "Guaanzhuang", align: "bottom", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 }, hideLabel: true },
    "M2208": { type: "no", x: 1572, y: 677, cn: "永顺", en: "Yongshun", align: "bottom", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 } },
    "M2209": { type: "no", x: 1615, y: 677, cn: "通州北关", en: "Tongzhou Beiguan", align: "bottom", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 }, hideLabel: true },
    "M2210": { type: "no", x: 1641, y: 691, cn: "芙蓉西路", en: "Furong Xilu", align: "top-right", offset: { x: 0, y: 6 }, textScale: { cn: 1, en: 1 } },
    "M2211": { type: "no", x: 1713, y: 728, cn: "北运河东", en: "Beiyunhedong", align: "bottom", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 }, hideLabel: true },
    "M2212": { type: "no", x: 1768, y: 695, cn: "潞源", en: "Luyuan", align: "top-left", offset: { x: 1, y: 2 }, textScale: { cn: 1, en: 1 } },
    "M2213": { type: "no", x: 1794, y: 669, cn: "潞源东", en: "Luyuandong", align: "top-left", offset: { x: 0, y: 3 }, textScale: { cn: 1, en: 1 } },
    "M2214": { type: "no", x: 1809, y: 568, cn: "燕郊", en: "Yanjiao", align: "left", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 } },
    "M2215": { type: "no", x: 1809, y: 524, cn: "神威大街", en: "Shenwei Dajie", align: "left", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 } },
    "M2216": { type: "no", x: 1809, y: 481, cn: "潮白大街", en: "Chaobai Dajie", align: "left", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 } },
    "M2217": { type: "no", x: 1809, y: 437, cn: "高楼", en: "Gaolou", align: "left", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 } },
    "M2218": { type: "no", x: 1809, y: 393, cn: "齐心庄", en: "Qixinzhuang", align: "left", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 } },
    "M2219": { type: "no", x: 1809, y: 349, cn: "马坊物流港", en: "Mafang Wuliugang", align: "left", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 } },
    "M2220": { type: "no", x: 1809, y: 305, cn: "马昌营", en: "Machangying", align: "left", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 } },
    "M2221": { type: "no", x: 1809, y: 261, cn: "国农港", en: "Guononggang", align: "left", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 } },
    "M2222": { type: "no", x: 1809, y: 217, cn: "平谷", en: "Pinggu", align: "left", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 } },
    "M2402": { type: "dot", x: 985, y: 982, cn: "肖村", en: "Xiaocun", align: "left", offset: { x: 0, y: 6 }, textScale: { cn: 1, en: 1 } },
    "M2403": { type: "dot", x: 998, y: 995, cn: "小红门", en: "Xiaohongmen", align: "top-right", offset: { x: 2, y: 8.5 }, textScale: { cn: 1, en: 1 } },
    "M2404": { type: "dot", x: 1011, y: 1008, cn: "旧宫", en: "Jiugong", align: "left", offset: { x: -1, y: 5.5 }, textScale: { cn: 1, en: 1 } },
    "M2405": { type: "dot", x: 1023, y: 1020, cn: "亦庄桥", en: "Yizhuangqiao", align: "top-right", offset: { x: 0.5, y: 9 }, textScale: { cn: 1, en: 1 } },
    "M2406": { type: "dot", x: 1036, y: 1033, cn: "亦庄文化园", en: "Yizhuang Culture Park", align: "left", offset: { x: -1, y: 5 }, textScale: { cn: 1, en: 1 } },
    "M2407": { type: "dot", x: 1048, y: 1045, cn: "万源街", en: "Wanyuanjie", align: "top-right", offset: { x: 1.5, y: 9 }, textScale: { cn: 1, en: 1 } },
    "M2408": { type: "dot", x: 1061, y: 1058, cn: "荣京东街", en: "Rongjing Dongjie", align: "left", offset: { x: -1, y: 5.5 }, textScale: { cn: 1, en: 1 } },
    "M2409": { type: "dot", x: 1083, y: 1080, cn: "荣昌东街", en: "Rongchang Dongjie", align: "top-right", offset: { x: 1, y: 6 }, textScale: { cn: 1, en: 1 } },
    "M2410": { type: "dot", x: 1176, y: 1095, cn: "同济南路", en: "Tongji Nanlu", align: "bottom", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 } },
    "M2411": { type: "dot", x: 1232, y: 1095, cn: "经海路", en: "Jinghailu", align: "bottom", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 } },
    "M2412": { type: "dot", x: 1290, y: 1095, cn: "次渠南", en: "Ciqunan", align: "bottom", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 } },
    "M2414": { type: "dot", x: 1405, y: 1058, cn: "亦庄火车站", en: "Yizhuang Rwy. Sta.", align: "bottom-right", offset: { x: -3, y: -4 }, textScale: { cn: 1, en: 1 } },
    "M2415": { type: "no", x: 1424, y: 1024, cn: "台湖", en: "Taihu", align: "top-right", offset: { x: -1, y: 4 }, textScale: { cn: 1, en: 1 } },
    "M2503": { type: "dot", x: 565, y: 987, cn: "花乡东桥", en: "Huaxiang Dongqiao", align: "right", offset: { x: 0, y: 4 }, textScale: { cn: 1, en: 1 } },
    "M2504": { type: "dot", x: 547, y: 1011, cn: "白盆窑", en: "Baipenyao", align: "bottom-right", offset: { x: -11, y: -1.5 }, textScale: { cn: 1, en: 1 } },
    "M2506": { type: "dot", x: 455, y: 1032, cn: "大葆台", en: "Dabaotai", align: "top-left", offset: { x: -2, y: 9.5 }, textScale: { cn: 1, en: 1 } },
    "M2507": { type: "dot", x: 442, y: 1045, cn: "稻田", en: "Daotian", align: "right", offset: { x: 1, y: 6 }, textScale: { cn: 1, en: 1 } },
    "M2508": { type: "dot", x: 429, y: 1058, cn: "长阳", en: "Changyang", align: "top-left", offset: { x: -1, y: 8.5 }, textScale: { cn: 1, en: 1 } },
    "M2509": { type: "dot", x: 416, y: 1071, cn: "篱笆房", en: "Libafang", align: "right", offset: { x: 1, y: 5 }, textScale: { cn: 1, en: 1 } },
    "M2510": { type: "dot", x: 403, y: 1084, cn: "广阳城", en: "Guangyangcheng", align: "top-left", offset: { x: -1, y: 8 }, textScale: { cn: 1, en: 1 } },
    "M2511": { type: "dot", x: 390, y: 1097, cn: "良乡大学城北", en: "Liangxiang Univ. Town North", align: "right", offset: { x: 1, y: 4 }, textScale: { cn: 1, en: 1 } },
    "M2512": { type: "dot", x: 377, y: 1110, cn: "良乡大学城", en: "Liangxiang Univ. Town", align: "top-left", offset: { x: 0, y: 7 }, textScale: { cn: 1, en: 1 } },
    "M2513": { type: "dot", x: 364, y: 1123, cn: "良乡大学城西", en: "Liangxiang Univ. Town West", align: "bottom-right", offset: { x: 2, y: -13 }, textScale: { cn: 1, en: 1 } },
    "M2514": { type: "dot", x: 351, y: 1136, cn: "良乡南关", en: "Liangxiang Nanguan", align: "bottom-right", offset: { x: -8, y: -0.5 }, textScale: { cn: 1, en: 1 } },
    "M2515": { type: "dot", x: 325, y: 1142, cn: "苏庄", en: "Suzhuang", align: "top", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 } },
    "M2516": { type: "tsf", x: 293, y: 1142, cn: "阎村东", en: "Yancundong", align: "bottom", offset: { x: 0, y: 4 }, textScale: { cn: 1, en: 1 } },
    "M25w2": { type: "dot", x: 260, y: 1142, cn: "紫草坞", en: "Zicaowu", align: "top", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 } },
    "M25w3": { type: "dot", x: 227, y: 1142, cn: "阎村", en: "Yancun", align: "bottom", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 } },
    "M25w4": { type: "dot", x: 195, y: 1142, cn: "星城", en: "Xingcheng", align: "top", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 } },
    "M25w5": { type: "dot", x: 162, y: 1142, cn: "大石河东", en: "Dashihedong", align: "bottom", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 } },
    "M25w6": { type: "dot", x: 129, y: 1142, cn: "马各庄", en: "Magezhuang", align: "top", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 } },
    "M25w7": { type: "dot", x: 97, y: 1142, cn: "饶乐府", en: "Raolefu", align: "bottom", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 } },
    "M25w8": { type: "dot", x: 70, y: 1122, cn: "房山城关", en: "Fangshan Chengguan", align: "top-right", offset: { x: -6.5, y: 0 }, textScale: { cn: 1, en: 0.95 } },
    "M25w9": { type: "dot", x: 50, y: 1102, cn: "燕山", en: "Yanshan", align: "top", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 } },
    "M2603": { type: "dot", x: 103, y: 675, cn: "四道桥", en: "Sidaoqiao", align: "left", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 } },
    "M2604": { type: "dot", x: 103, y: 701, cn: "桥户营", en: "Qiaohuying", align: "right", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 } },
    "M2605": { type: "dot", x: 103, y: 727, cn: "上岸", en: "Shang'an", align: "right", offset: { x: 0, y: -1 }, textScale: { cn: 1, en: 1 } },
    "M2606": { type: "dot", x: 103, y: 753, cn: "栗园庄", en: "Liyuanzhuang", align: "right", offset: { x: 0, y: -2 }, textScale: { cn: 1, en: 1 } },
    "M2607": { type: "dot", x: 78, y: 767, cn: "小园", en: "Xiaoyuan", align: "bottom", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 } },
    "M2608": { type: "dot", x: 50, y: 767, cn: "石厂", en: "Shichang", align: "top", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 } },
    "M2701": { type: "dot", x: 431, y: 55, cn: "昌平西山口", en: "Changping Xishankou", align: "top", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 } },
    "M2702": { type: "dot", x: 505, y: 55, cn: "十三陵景区", en: "Ming Tombs", align: "top", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 } },
    "M2703": { type: "dot", x: 582, y: 90, cn: "昌平", en: "Changping", align: "top", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 } },
    "M2704": { type: "dot", x: 636, y: 90, cn: "昌平东关", en: "Changping Dongguan", align: "top", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 } },
    "M2705": { type: "dot", x: 690, y: 90, cn: "北邵洼", en: "Beishaowa", align: "top", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 } },
    "M2706": { type: "dot", x: 713, y: 105, cn: "南邵", en: "Nanshao", align: "right", offset: { x: 0, y: -5 }, textScale: { cn: 1, en: 1 } },
    "M2707": { type: "dot", x: 713, y: 126.1, cn: "沙河高教园", en: "Shahe Univ. Park", align: "right", offset: { x: 0, y: -3 }, textScale: { cn: 1, en: 1 } },
    "M2708": { type: "dot", x: 713, y: 147, cn: "沙河", en: "Shahe", align: "right", offset: { x: 0, y: -1.5 }, textScale: { cn: 1, en: 1 } },
    "M2709": { type: "dot", x: 713, y: 168, cn: "巩华城", en: "Gonghuacheng", align: "right", offset: { x: 0, y: 0.5 }, textScale: { cn: 1, en: 0.95 } },
    "M2711": { type: "dot", x: 690, y: 215, cn: "生命科学园", en: "Life Science Park", align: "right", offset: { x: 0, y: 6.5 }, textScale: { cn: 0.95, en: 1 } },
    "M2714": { type: "dot", x: 684, y: 328, cn: "朱房北", en: "Zhufangbei", align: "top", offset: { x: 11, y: 0 }, textScale: { cn: 1, en: 0.95 } },
    "M2715": { type: "dot", x: 698, y: 340, cn: "清河小营桥", en: "Qinghe Xiaoyingqiao", align: "top-right", offset: { x: 0.5, y: 10.5 }, textScale: { cn: 1, en: 1 } },
    "M2716": { type: "dot", x: 698, y: 357, cn: "学知园", en: "Xuezhiyuan", align: "right", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 } },
    "M2718": { type: "dot", x: 698, y: 420, cn: "学院桥", en: "Xueyuanqiao", align: "right", offset: { x: 0, y: -1 }, textScale: { cn: 1, en: 0.9 } },
    "M302": { type: "tsf", x: 1110, y: 623, cn: "工人体育场", en: "Workers' Stadium", align: "top-left", offset: { x: 0, y: 0 }, textScale: { cn: 0.9, en: 0.9 } },
    "M303": { type: "tsf", x: 1177, y: 623, cn: "团结湖", en: "Tuanjiehu", align: "top-left", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 } },
    "M304": { type: "tsf", x: 1240, y: 623, cn: "朝阳公园", en: "Chaoyang Park", align: "top-left", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 } },
    "M305": { type: "dot", x: 1296, y: 623, cn: "石佛营", en: "Shifoying", align: "top", offset: { x: 0, y: -1 }, textScale: { cn: 1, en: 1 } },
    "M306": { type: "dot", x: 1336, y: 600, cn: "朝阳站", en: "Chaoyang Rwy. Sta.", align: "bottom-right", offset: { x: 2, y: -10 }, textScale: { cn: 1, en: 0.95 } },
    "M307": { type: "dot", x: 1354, y: 581, cn: "姚家园", en: "Yaojiayuan", align: "right", offset: { x: 1, y: 2 }, textScale: { cn: 1, en: 1 } },
    "M308": { type: "dot", x: 1355, y: 557.5, cn: "东坝南", en: "Dongbanan", align: "right", offset: { x: 0, y: 2 }, textScale: { cn: 1, en: 1 } },
    "M309": { type: "dot", x: 1355, y: 534, cn: "东坝", en: "Dongba", align: "right", offset: { x: 0, y: 2 }, textScale: { cn: 1, en: 1 } },
    "M310": { type: "tsf", x: 1408, y: 515, cn: "东坝北", en: "Dongbabei", align: "top", offset: { x: 0, y: -5.5 }, textScale: { cn: 1, en: 1 } },
    "M401": { type: "dot", x: 399, y: 380, cn: "安河桥北", en: "Anheqiaobei", align: "top", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 } },
    "M402": { type: "dot", x: 443, y: 380, cn: "北宫门", en: "Beigongmen", align: "bottom", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 } },
    "M403": { type: "tsf", x: 492, y: 380, cn: "西苑", en: "Xiyuan", align: "top-left", offset: { x: 0, y: 1 }, textScale: { cn: 1, en: 1 } },
    "M404": { type: "dot", x: 532, y: 380, cn: "圆明园", en: "Yuanmingyuan Park", align: "top", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 0.95 } },
    "M405": { type: "dot", x: 547, y: 401, cn: "北京大学东门", en: "Peking Univ.<br>East Gate", align: "right", offset: { x: 0, y: -8.5 }, textScale: { cn: 1, en: 1 } },
    "M406": { type: "dot", x: 547, y: 424.9, cn: "中关村", en: "Zhongguancun", align: "right", offset: { x: 0, y: -5 }, textScale: { cn: 1, en: 1 } },
    "M407": { type: "tsf", x: 547, y: 460, cn: "海淀黄庄", en: "Haidian Huangzhuang", align: "top-right", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 } },
    "M408": { type: "tsf", x: 547, y: 511, cn: "人民大学", en: "Renmin Univ.", align: "bottom-right", offset: { x: 0, y: -1 }, textScale: { cn: 1, en: 1 } },
    "M409": { type: "dot", x: 547, y: 541, cn: "魏公村", en: "Weigongcun", align: "left", offset: { x: 0, y: -2.5 }, textScale: { cn: 1, en: 1 } },
    "M410": { type: "tsf", x: 547, y: 572, cn: "国家图书馆", en: "National Library", align: "top-right", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 } },
    "M411": { type: "dot", x: 660, y: 588, cn: "动物园", en: "Beijing Zoo", align: "top", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 } },
    "M413": { type: "dot", x: 761, y: 593, cn: "新街口", en: "Xinjiekou", align: "bottom-left", offset: { x: 2, y: -6 }, textScale: { cn: 1, en: 1 } },
    "M414": { type: "tsf", x: 765, y: 623, cn: "平安里", en: "Ping'anli", align: "bottom-right", offset: { x: 0, y: -1 }, textScale: { cn: 1, en: 1 } },
    "M415": { type: "dot", x: 765, y: 658, cn: "西四", en: "Xisi", align: "right", offset: { x: 0, y: 4 }, textScale: { cn: 1, en: 1 } },
    "M416": { type: "dot", x: 765, y: 688, cn: "灵境胡同", en: "Lingjing Hutong", align: "right", offset: { x: 0, y: -2 }, textScale: { cn: 1, en: 1 } },
    "M419": { type: "tsf", x: 765, y: 812, cn: "菜市口", en: "Caishikou", align: "bottom-left", offset: { x: 0, y: -2 }, textScale: { cn: 1, en: 1 } },
    "M420": { type: "dot", x: 765, y: 843, cn: "陶然亭", en: "Taoranting", align: "right", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 } },
    "M421": { type: "tsf", x: 765, y: 874, cn: "北京南站", en: "Beijingnan Rwy. Sta.", align: "bottom-right", offset: { x: 0, y: -1.5 }, textScale: { cn: 1, en: 1 } },
    "M422": { type: "dot", x: 765, y: 911, cn: "马家堡", en: "Majiapu", align: "left", offset: { x: 0, y: 2.5 }, textScale: { cn: 1, en: 1 } },
    "M423": { type: "tsf", x: 765, y: 948, cn: "角门西", en: "Jiaomenxi", align: "top-right", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 } },
    "M424": { type: "dot", x: 765, y: 971, cn: "公益西桥", en: "Gongyi Xiqiao", align: "right", offset: { x: 0, y: -1.5 }, textScale: { cn: 1, en: 1 } },
    "M425": { type: "tsf", x: 765, y: 993, cn: "新宫", en: "Xingong", align: "right", offset: { x: 4.5, y: -1 }, textScale: { cn: 1, en: 1 } },
    "M426": { type: "dot", x: 681, y: 1028.5, cn: "西红门", en: "Xihongmen", align: "left", offset: { x: 0, y: -3 }, textScale: { cn: 1, en: 1 } },
    "M427": { type: "dot", x: 681, y: 1051, cn: "高米店北", en: "Gaomidianbei", align: "left", offset: { x: 0, y: -3 }, textScale: { cn: 1, en: 1 } },
    "M428": { type: "dot", x: 681, y: 1073.5, cn: "高米店南", en: "Gaomidiannan", align: "left", offset: { x: 0, y: -3 }, textScale: { cn: 1, en: 1 } },
    "M429": { type: "dot", x: 681, y: 1096, cn: "枣园", en: "Zaoyuan", align: "left", offset: { x: 0, y: -3 }, textScale: { cn: 1, en: 1 } },
    "M430": { type: "dot", x: 681, y: 1118.5, cn: "清源路", en: "Qingyuanlu", align: "left", offset: { x: 0, y: -3 }, textScale: { cn: 1, en: 1 } },
    "M431": { type: "dot", x: 681, y: 1141, cn: "黄村西大街", en: "Huangcun Xidajie", align: "left", offset: { x: 0, y: -3 }, textScale: { cn: 1, en: 1 } },
    "M432": { type: "dot", x: 681, y: 1163.5, cn: "黄村火车站", en: "Huangcun Rwy. Sta.", align: "left", offset: { x: 0, y: -3 }, textScale: { cn: 1, en: 1 } },
    "M433": { type: "dot", x: 681, y: 1186, cn: "义和庄", en: "Yihezhuang", align: "left", offset: { x: 0, y: -3 }, textScale: { cn: 1, en: 1 } },
    "M434": { type: "dot", x: 681, y: 1208.5, cn: "生物医药基地", en: "Biomedical Base", align: "left", offset: { x: 0, y: -3 }, textScale: { cn: 1, en: 1 } },
    "M435": { type: "dot", x: 681, y: 1231, cn: "天宫院", en: "Tiangongyuan", align: "left", offset: { x: 0, y: -3 }, textScale: { cn: 1, en: 1 } },
    "M501": { type: "dot", x: 978, y: 199, cn: "天通苑北", en: "Tiantongyuanbei", align: "right", offset: { x: 0, y: -2 }, textScale: { cn: 1, en: 1 } },
    "M502": { type: "tsf", x: 978, y: 237, cn: "天通苑", en: "Tiantongyuan", align: "top-right", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 0.9 } },
    "M503": { type: "dot", x: 978, y: 262, cn: "天通苑南", en: "Tiantongyuannan", align: "right", offset: { x: 0, y: -5.5 }, textScale: { cn: 1, en: 1 } },
    "M504": { type: "tsf", x: 978, y: 293, cn: "立水桥", en: "Lishuiqiao", align: "top-right", offset: { x: 1, y: 3.5 }, textScale: { cn: 1, en: 1 } },
    "M505": { type: "dot", x: 978, y: 322, cn: "立水桥南", en: "Lishuiqiaonan", align: "right", offset: { x: 0, y: -1 }, textScale: { cn: 1, en: 1 } },
    "M506": { type: "dot", x: 978, y: 344, cn: "北苑路北", en: "Beiyuanlubei", align: "right", offset: { x: 0, y: -1 }, textScale: { cn: 1, en: 1 } },
    "M507": { type: "tsf", x: 978, y: 380, cn: "大屯路东", en: "Datunludong", align: "top-right", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 } },
    "M508": { type: "dot", x: 978, y: 420, cn: "惠新西街北口", en: "Huixin Xijie Beikou", align: "right", offset: { x: 0, y: -1 }, textScale: { cn: 1, en: 1 } },
    "M509": { type: "tsf", x: 978, y: 460, cn: "惠新西街南口", en: "Huixin Xijie Nankou", align: "top-right", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 0.95 } },
    "M510": { type: "tsf", x: 978, y: 511, cn: "和平西桥", en: "Heping Xiqiao", align: "top-right", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 } },
    "M511": { type: "dot", x: 978, y: 533, cn: "和平里北街", en: "Hepingli Beijie", align: "right", offset: { x: 0, y: -1.5 }, textScale: { cn: 1, en: 1 } },
    "M513": { type: "dot", x: 978, y: 591, cn: "北新桥", en: "Beixinqiao", align: "left", offset: { x: 0, y: 1.5 }, textScale: { cn: 1, en: 1 } },
    "M514": { type: "dot", x: 978, y: 623, cn: "张自忠路", en: "Zhangzizhonglu", align: "left", offset: { x: 0, y: -6.5 }, textScale: { cn: 1, en: 0.95 } },
    "M515": { type: "tsf", x: 978, y: 656, cn: "东四", en: "Dongsi", align: "top-left", offset: { x: 0, y: 1 }, textScale: { cn: 1, en: 1 } },
    "M516": { type: "dot", x: 978, y: 687, cn: "灯市口", en: "Dengshikou", align: "right", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 } },
    "M519": { type: "tsf", x: 978, y: 812, cn: "磁器口", en: "Ciqikou", align: "top-right", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 } },
    "M520": { type: "dot", x: 978, y: 843, cn: "天坛东门", en: "Temple of Heaven<br>East Gate", align: "left", offset: { x: 0, y: -4 }, textScale: { cn: 1, en: 0.95 } },
    "M521": { type: "tsf", x: 978, y: 874, cn: "蒲黄榆", en: "Puhuangyu", align: "bottom-right", offset: { x: 0, y: -1.5 }, textScale: { cn: 1, en: 1 } },
    "M522": { type: "dot", x: 978, y: 911, cn: "刘家窑", en: "Liujiayao", align: "right", offset: { x: 0, y: 2 }, textScale: { cn: 1, en: 1 } },
    "M523": { type: "tsf", x: 978, y: 948, cn: "宋家庄", en: "Songjiazhuang", align: "bottom-right", offset: { x: 0, y: -2 }, textScale: { cn: 1, en: 1 } },
    "M601": { type: "tsf", x: 157, y: 656, cn: "金安桥", en: "Jin'anqiao", align: "bottom-left", offset: { x: 0, y: 3 }, textScale: { cn: 1, en: 1 } },
    "M602": { type: "tsf", x: 209, y: 656, cn: "苹果园", en: "Pingguoyuan", align: "bottom-left", offset: { x: 6, y: 3 }, textScale: { cn: 1, en: 1 } },
    "M603": { type: "dot", x: 252, y: 623, cn: "杨庄", en: "Yangzhuang", align: "top", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 } },
    "M604": { type: "dot", x: 288, y: 623, cn: "西黄村", en: "Xihuangcun", align: "bottom", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 0.95 } },
    "M605": { type: "dot", x: 325, y: 623, cn: "廖公庄", en: "Liaogongzhuang", align: "top", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 } },
    "M606": { type: "dot", x: 362, y: 623, cn: "田村", en: "Tiancun", align: "bottom", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 } },
    "M607": { type: "dot", x: 399, y: 623, cn: "海淀五路居", en: "Haidian Wuluju", align: "top", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 } },
    "M608": { type: "tsf", x: 435, y: 623, cn: "慈寿寺", en: "Cishousi", align: "top-right", offset: { x: 0, y: 0.5 }, textScale: { cn: 1, en: 1 } },
    "M609": { type: "dot", x: 491, y: 623, cn: "花园桥", en: "Huayuanqiao", align: "bottom", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 } },
    "M610": { type: "tsf", x: 547, y: 623, cn: "白石桥南", en: "Baishiqiaonan", align: "bottom-right", offset: { x: 0, y: -1 }, textScale: { cn: 1, en: 1 } },
    "M611": { type: "tsf", x: 620, y: 623, cn: "二里沟", en: "Erligou", align: "top-left", offset: { x: 0, y: 0.5 }, textScale: { cn: 1, en: 1 } },
    "M612": { type: "dot", x: 660, y: 623, cn: "车公庄西", en: "Chegongzhuangxi", align: "top", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 } },
    "M615": { type: "dot", x: 824, y: 623, cn: "北海北", en: "Beihaibei", align: "top", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 } },
    "M616": { type: "tsf", x: 881, y: 623, cn: "南锣鼓巷", en: "Nanluoguxiang", align: "bottom-left", offset: { x: 0, y: -1 }, textScale: { cn: 1, en: 1 } },
    "M619": { type: "tsf", x: 1110, y: 656, cn: "东大桥", en: "Dongdaqiao", align: "top-left", offset: { x: 0, y: 1 }, textScale: { cn: 1, en: 1 } },
    "M620": { type: "tsf", x: 1177, y: 656, cn: "呼家楼", en: "Hujialou", align: "top-left", offset: { x: 0, y: 1 }, textScale: { cn: 1, en: 1 } },
    "M621": { type: "tsf", x: 1240, y: 656, cn: "金台路", en: "Jintailu", align: "top-left", offset: { x: 0, y: 1 }, textScale: { cn: 1, en: 1 } },
    "M622": { type: "dot", x: 1296, y: 656, cn: "十里堡", en: "Shilipu", align: "top", offset: { x: 0, y: -1 }, textScale: { cn: 1, en: 1 } },
    "M623": { type: "dot", x: 1361, y: 656, cn: "青年路", en: "Qingnianlu", align: "top", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 } },
    "M624": { type: "dot", x: 1430, y: 656, cn: "褡裢坡", en: "Dalianpo", align: "top", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 } },
    "M625": { type: "dot", x: 1476, y: 656, cn: "黄渠", en: "Huangqu", align: "bottom", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 } },
    "M626": { type: "dot", x: 1500.5, y: 656, cn: "常营", en: "Changying", align: "top", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 } },
    "M627": { type: "dot", x: 1525, y: 656, cn: "草房", en: "Caofang", align: "bottom", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 } },
    "M628": { type: "dot", x: 1561, y: 656, cn: "物资学院路", en: "Wuzixueyuanlu", align: "top", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 } },
    "M629": { type: "dot", x: 1615, y: 677, cn: "通州北关", en: "Tongzhou<br>Beiguan", align: "top-right", offset: { x: -7, y: 1.5 }, textScale: { cn: 1, en: 1 } },
    "M630": { type: "dot", x: 1641, y: 703, cn: "通运门", en: "Tongyunmen", align: "bottom-left", offset: { x: 1, y: -6 }, textScale: { cn: 1, en: 1 } },
    "M631": { type: "dot", x: 1663, y: 725, cn: "北运河西", en: "Beiyunhexi", align: "bottom-left", offset: { x: 0, y: -7 }, textScale: { cn: 1, en: 1 } },
    "M632": { type: "dot", x: 1693, y: 741, cn: "北运河东", en: "Beiyunhedong", align: "bottom", offset: { x: -14, y: -1 }, textScale: { cn: 1, en: 1 } },
    "M633": { type: "dot", x: 1742, y: 741, cn: "郝家府", en: "Haojiafu", align: "bottom", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 } },
    "M634": { type: "dot", x: 1768, y: 741, cn: "东夏园", en: "Dongxiayuan", align: "top", offset: { x: 0, y: -0.5 }, textScale: { cn: 1, en: 1 } },
    "M635": { type: "dot", x: 1794, y: 741, cn: "潞城", en: "Lucheng", align: "bottom", offset: { x: -6, y: 0 }, textScale: { cn: 1, en: 1 } },
    "M636": { type: "dot", x: 1809, y: 778, cn: "潞阳", en: "Luyang", align: "bottom-left", offset: { x: 0, y: -9 }, textScale: { cn: 1, en: 1 } },
    "M701": { type: "tsf", x: 547, y: 779, cn: "北京西站", en: "Beijingxi Rwy. Sta.", align: "top-right", offset: { x: 0.5, y: -14.5 }, textScale: { cn: 1, en: 1 } },
    "M702": { type: "dot", x: 578, y: 808, cn: "湾子", en: "Wanzi", align: "top-right", offset: { x: -2, y: 4 }, textScale: { cn: 1, en: 1 } },
    "M703": { type: "tsf", x: 620, y: 812, cn: "达官营", en: "Daguanying", align: "bottom-left", offset: { x: 0, y: -2 }, textScale: { cn: 1, en: 1 } },
    "M704": { type: "tsfo", x: 704, y: 812, cn: "广安门内", en: "Guang'anmennei", align: "top-left", offset: { x: 5, y: 0 }, textScale: { cn: 1, en: 1 } },
    "M706": { type: "dot", x: 804, y: 812, cn: "虎坊桥", en: "Hufangqiao", align: "top", offset: { x: 0, y: -1 }, textScale: { cn: 1, en: 1 } },
    "M707": { type: "tsf", x: 872, y: 812, cn: "珠市口", en: "Zhushikou", align: "top-left", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 } },
    "M708": { type: "dot", x: 925, y: 812, cn: "桥湾", en: "Qiaowan", align: "top", offset: { x: 0, y: -1 }, textScale: { cn: 1, en: 1 } },
    "M710": { type: "dot", x: 1040, y: 812, cn: "广渠门内", en: "Guangqumennei", align: "bottom", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 } },
    "M711": { type: "dot", x: 1102, y: 812, cn: "广渠门外", en: "Guangqumenwai", align: "top-left", offset: { x: 8, y: 0 }, textScale: { cn: 1, en: 1 } },
    "M712": { type: "tsf", x: 1177, y: 812, cn: "双井", en: "Shuangjing", align: "top-left", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 } },
    "M713": { type: "tsf", x: 1240, y: 812, cn: "九龙山", en: "Jiulongshan", align: "top-left", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 } },
    "M714": { type: "dot", x: 1286, y: 812, cn: "大郊亭", en: "Dajiaoting", align: "top", offset: { x: 0, y: -1 }, textScale: { cn: 1, en: 1 } },
    "M715": { type: "dot", x: 1330, y: 812, cn: "百子湾", en: "Baiziwan", align: "top", offset: { x: 0, y: -1 }, textScale: { cn: 1, en: 1 } },
    "M716": { type: "dot", x: 1346, y: 841, cn: "化工", en: "Huagong", align: "right", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 } },
    "M717": { type: "dot", x: 1346, y: 865, cn: "南楼梓庄", en: "Nanlouzizhuang", align: "right", offset: { x: 0, y: 1.5 }, textScale: { cn: 1, en: 1 } },
    "M718": { type: "dot", x: 1346, y: 890, cn: "欢乐谷景区", en: "Happy Valley", align: "left", offset: { x: 0, y: 4.5 }, textScale: { cn: 1, en: 1 } },
    "M719": { type: "dot", x: 1366, y: 911, cn: "垡头", en: "Fatou", align: "bottom", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 } },
    "M720": { type: "dot", x: 1397, y: 911, cn: "双合", en: "Shuanghe", align: "top", offset: { x: 0, y: -1 }, textScale: { cn: 1, en: 1 } },
    "M721": { type: "dot", x: 1428.8, y: 911, cn: "焦化厂", en: "Jiaohuachang", align: "bottom", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 } },
    "M722": { type: "dot", x: 1460.5, y: 911, cn: "黄厂", en: "Huangchang", align: "top", offset: { x: 0, y: -1 }, textScale: { cn: 1, en: 1 } },
    "M723": { type: "dot", x: 1492, y: 911, cn: "郎辛庄", en: "Langxinzhuang", align: "bottom", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 } },
    "M724": { type: "dot", x: 1523, y: 911, cn: "黑庄户", en: "Heizhuanghu", align: "top", offset: { x: 0, y: -1 }, textScale: { cn: 1, en: 1 } },
    "M725": { type: "dot", x: 1554, y: 911, cn: "万盛西", en: "Wanshengxi", align: "bottom", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 } },
    "M726": { type: "dot", x: 1585, y: 911, cn: "万盛东", en: "Wanshengdong", align: "top", offset: { x: 0, y: -1 }, textScale: { cn: 1, en: 1 } },
    "M727": { type: "dot", x: 1616, y: 911, cn: "群芳", en: "Qunfang", align: "bottom", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 } },
    "M728": { type: "dot", x: 1648, y: 911, cn: "高楼金", en: "Gaoloujin", align: "top", offset: { x: 0, y: -1 }, textScale: { cn: 1, en: 1 } },
    "M801": { type: "tsf", x: 713, y: 192, cn: "朱辛庄", en: "Zhuxinzhuang", align: "left", offset: { x: -5, y: -6 }, textScale: { cn: 1, en: 1 } },
    "M802": { type: "dot", x: 788, y: 203, cn: "育知路", en: "Yuzhilu", align: "top", offset: { x: 0, y: -1 }, textScale: { cn: 1, en: 1 } },
    "M803": { type: "dot", x: 841, y: 203, cn: "平西府", en: "Pingxifu", align: "top", offset: { x: 0, y: -1 }, textScale: { cn: 1, en: 1 } },
    "M804": { type: "tsf", x: 872, y: 237, cn: "回龙观东大街", en: "Huilongguan Dongdajie", align: "top-right", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 } },
    "M805": { type: "tsf", x: 872, y: 270, cn: "霍营", en: "Huoying", align: "top-right", offset: { x: 0, y: 0.5 }, textScale: { cn: 1, en: 1 } },
    "M806": { type: "dot", x: 872, y: 294.2, cn: "育新", en: "Yuxin", align: "left", offset: { x: 0, y: 2 }, textScale: { cn: 1, en: 1 } },
    "M807": { type: "dot", x: 872, y: 310.3, cn: "西小口", en: "Xixiaokou", align: "right", offset: { x: 0, y: 1 }, textScale: { cn: 1, en: 1 } },
    "M808": { type: "dot", x: 872, y: 326.3, cn: "永泰庄", en: "Yongtaizhuang", align: "left", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 0.95 } },
    "M809": { type: "dot", x: 872, y: 342.3, cn: "林萃桥", en: "Lincuiqiao", align: "right", offset: { x: 0, y: -1 }, textScale: { cn: 1, en: 1 } },
    "M810": { type: "dot", x: 872, y: 358.4, cn: "森林公园南门", en: "Forest Park South Gate", align: "left", offset: { x: 0, y: -2 }, textScale: { cn: 0.9, en: 0.9 } },
    "M811": { type: "tsf", x: 872, y: 380, cn: "奥林匹克公园", en: "Olympic Park", align: "bottom-right", offset: { x: 0, y: -2 }, textScale: { cn: 1, en: 1 } },
    "M812": { type: "dot", x: 872, y: 420, cn: "奥体中心", en: "Olympic Sports Center", align: "right", offset: { x: 0, y: -1 }, textScale: { cn: 1, en: 1 } },
    "M813": { type: "tsf", x: 872, y: 460, cn: "北土城", en: "Beitucheng", align: "top-right", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 } },
    "M814": { type: "tsf", x: 872, y: 511, cn: "安华桥", en: "Anhuaqiao", align: "top-right", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 } },
    "M815": { type: "dot", x: 872, y: 533, cn: "安德里北街", en: "Andeli Beijie", align: "left", offset: { x: 0, y: -1.5 }, textScale: { cn: 1, en: 1 } },
    "M817": { type: "dot", x: 872, y: 591, cn: "什刹海", en: "Shichahai", align: "right", offset: { x: 0, y: 1.5 }, textScale: { cn: 1, en: 1 } },
    "M819": { type: "dot", x: 910, y: 652, cn: "中国美术馆", en: "National Art Museum", align: "bottom-left", offset: { x: 0.5, y: -6.5 }, textScale: { cn: 1, en: 1 } },
    "M820": { type: "dot", x: 920, y: 687, cn: "金鱼胡同", en: "Jinyu Hutong", align: "right", offset: { x: 0, y: 0 }, textScale: { cn: 0.95, en: 1 } },
    "M824": { type: "dot", x: 872, y: 843, cn: "天桥", en: "Tianqiao", align: "right", offset: { x: 0, y: -7.5 }, textScale: { cn: 1, en: 1 } },
    "M825": { type: "tsf", x: 872, y: 874, cn: "永定门外", en: "Yongdingmenwai", align: "top-right", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 } },
    "M826": { type: "dot", x: 872, y: 900, cn: "木樨园", en: "Muxiyuan", align: "right", offset: { x: 0, y: -1 }, textScale: { cn: 1, en: 1 } },
    "M827": { type: "dot", x: 872, y: 922, cn: "海户屯", en: "Haihutun", align: "right", offset: { x: 0, y: 1 }, textScale: { cn: 1, en: 1 } },
    "M828": { type: "tsf", x: 872, y: 948, cn: "大红门", en: "Dahongmen", align: "bottom-right", offset: { x: 0, y: -2 }, textScale: { cn: 1, en: 1 } },
    "M829": { type: "dot", x: 872, y: 983, cn: "大红门南", en: "Dahongmennan", align: "right", offset: { x: 0, y: 5 }, textScale: { cn: 1, en: 1 } },
    "M830": { type: "dot", x: 880, y: 1010, cn: "和义", en: "Heyi", align: "left", offset: { x: -4, y: 3 }, textScale: { cn: 1, en: 1 } },
    "M831": { type: "dot", x: 903, y: 1033, cn: "东高地", en: "Donggaodi", align: "left", offset: { x: -2, y: 5 }, textScale: { cn: 1, en: 1 } },
    "M832": { type: "dot", x: 926, y: 1056, cn: "火箭万源", en: "Huojian Wanyuan", align: "left", offset: { x: -1, y: 7 }, textScale: { cn: 1, en: 1 } },
    "M833": { type: "dot", x: 949, y: 1079, cn: "五福堂", en: "Wufutang", align: "left", offset: { x: 1, y: 10 }, textScale: { cn: 1, en: 1 } },
    "M834": { type: "dot", x: 972, y: 1102, cn: "德茂", en: "Demao", align: "left", offset: { x: 3, y: 12 }, textScale: { cn: 1, en: 1 } },
    "M835": { type: "dot", x: 994, y: 1124, cn: "瀛海", en: "Yinghai", align: "bottom", offset: { x: -6, y: 0 }, textScale: { cn: 1, en: 1 } },
    "M903": { type: "dot", x: 547, y: 658, cn: "白堆子", en: "Baiduizi", align: "left", offset: { x: 0, y: 4 }, textScale: { cn: 1, en: 1 } },
    "M906": { type: "dot", x: 525, y: 799, cn: "六里桥东", en: "Liuliqiaodong", align: "bottom-right", offset: { x: -7, y: -0.5 }, textScale: { cn: 0.95, en: 1 } },
    "M907": { type: "tsf", x: 505, y: 819, cn: "六里桥", en: "Liuliqiao", align: "left", offset: { x: -5, y: -4 }, textScale: { cn: 1, en: 1 } },
    "M908": { type: "tsf", x: 476, y: 874, cn: "七里庄", en: "Qilizhuang", align: "top-left", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 } },
    "M909": { type: "dot", x: 476, y: 911, cn: "丰台东大街", en: "Fengtai Dongdajie", align: "left", offset: { x: 0, y: -7 }, textScale: { cn: 1, en: 1 } },
    "M910": { type: "tsf", x: 476, y: 948, cn: "丰台南路", en: "Fengtai Nanlu", align: "top-left", offset: { x: 0, y: -0.5 }, textScale: { cn: 1, en: 1 } },
    "M911": { type: "dot", x: 476, y: 969, cn: "科怡路", en: "Keyilu", align: "left", offset: { x: 0, y: -1 }, textScale: { cn: 1, en: 1 } },
    "M912": { type: "dot", x: 476, y: 987, cn: "丰台科技园", en: "Fengtai Science Park", align: "right", offset: { x: 0, y: 3.5 }, textScale: { cn: 1, en: 1 } },
    "M913": { type: "tsf", x: 476, y: 1011, cn: "郭公庄", en: "Guogongzhuang", align: "bottom-right", offset: { x: 0, y: -1.5 }, textScale: { cn: 1, en: 1 } },
    "Rwy01": { type: "rdot", x: 702, y: 1163.5, cn: "北京大兴站", en: "Beijing Daxing Rwy. Sta.", align: "right", offset: { x: 0, y: -3 }, textScale: { cn: 1, en: 1 } },
    "Rwy02": { type: "rdot", x: 1707.1, y: 728, cn: "北京通州站", en: "Beijing Tongzhou<br>Rwy. Sta.", align: "top", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 } },
    "S101": { type: "dot", x: 293, y: 1096, cn: "良乡站", en: "Liangxiang Rwy. Sta.", align: "left", offset: { x: -0.5, y: 5 }, textScale: { cn: 1, en: 1 } },
    "S102": { type: "dot", x: 561, y: 765, cn: "北京西站", en: "Beijingxi Rwy. Sta.", align: "right", offset: { x: 1, y: 6 }, textScale: { cn: 1, en: 1 }, hideLabel: true },
    "S103": { type: "dot", x: 1040, y: 778, cn: "北京站", en: "Beijing Rwy. Sta.", align: "right", offset: { x: 1, y: 6 }, textScale: { cn: 1, en: 1 }, hideLabel: true },
    "S104": { type: "dot", x: 1263, y: 778, cn: "北京东站", en: "Beijingdong Rwy. Sta.", align: "top-right", offset: { x: -11, y: 0 }, textScale: { cn: 1, en: 1 } },
    "S105": { type: "dot", x: 1662, y: 778, cn: "中仓站", en: "Zhongcang Rwy. Sta.", align: "bottom", offset: { x: 0, y: -0.5 }, textScale: { cn: 1, en: 0.95 } },
    "S106": { type: "dot", x: 1706, y: 810, cn: "乔庄东站", en: "Qiaozhuangdong<br>Rwy. Sta.", align: "left", offset: { x: 0, y: 9 }, textScale: { cn: 1, en: 0.9 } },
    "S107": { type: "dot", x: 293, y: 1058, cn: "房山东站", en: "Fangshandong Rwy. Sta.", align: "right", offset: { x: 0, y: -7.5 }, textScale: { cn: 1, en: 1 } },
    "S108": { type: "dot", x: 241, y: 960, cn: "后吕村站", en: "Houlyucun Ryw. Sta.", align: "left", offset: { x: -5, y: 0 }, textScale: { cn: 1, en: 1 } },
    "S109": { type: "dot", x: 325, y: 778, cn: "衙门口东站", en: "Yamenkoudong Rwy. Sta.", align: "bottom", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 } },
    "S201": { type: "dot", x: 479, y: 90, cn: "南口站", en: "Nankou<br>Rwy. Sta.", align: "bottom", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 } },
    "S202": { type: "dot", x: 431, y: 90, cn: "八达岭站", en: "Badaling<br>Rwy. Sta.", align: "bottom", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 } },
    "S203": { type: "dot", x: 377, y: 90, cn: "康庄站", en: "Kangzhuang<br>Rwy. Sta.", align: "bottom", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 } },
    "S204": { type: "dot", x: 325, y: 90, cn: "沙城站", en: "Shacheng<br>Rwy. Sta.", align: "bottom", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 } },
    "S205": { type: "dot", x: 326, y: 55, cn: "延庆站", en: "Yanqing Rwy. Sta.", align: "top", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 } },
    "S501": { type: "dot", x: 698, y: 548, cn: "北京北站", en: "Beijingbei Rwy. Sta.", align: "right", offset: { x: 0, y: -9.5 }, textScale: { cn: 1, en: 1 } },
    "S502": { type: "dot", x: 663, y: 299, cn: "清河站", en: "Qinghe Rwy. Sta.", align: "right", offset: { x: 3, y: -6.5 }, textScale: { cn: 1, en: 1 }, hideLabel: true },
    "S503": { type: "dot", x: 582, y: 55, cn: "昌平北站", en: "Changpingbei Rwy. Sta.", align: "top", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 } },
    "S504": { type: "tsfo", x: 1596, y: 55, cn: "雁栖湖站", en: "Yanqihu<br>Rwy. Sta.", align: "bottom-left", offset: { x: 0, y: -1 }, textScale: { cn: 1, en: 1 } },
    "S505": { type: "tsfo", x: 1639, y: 55, cn: "怀柔北站", en: "Huairoubei Rwy. Sta.", align: "top", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 }, hideLabel: true },
    "S506": { type: "dot", x: 1683, y: 55, cn: "黑山寺站", en: "Heishansi Rwy. Sta.", align: "bottom", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 } },
    "S507": { type: "dot", x: 1726, y: 55, cn: "古北口站", en: "Gubeikou Rwy. Sta.", align: "top", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 } },
    "S601": { type: "dot", x: 1548, y: 760, cn: "通州西站", en: "Tongzhouxi Rwy. Sta.", align: "left", offset: { x: 0, y: 2 }, textScale: { cn: 1, en: 1 } },
    "S602": { type: "tsfo", x: 1596, y: 216, cn: "顺义站", en: "Shunyi Rwy. Sta.", align: "right", offset: { x: 0, y: 1 }, textScale: { cn: 1, en: 1 } },
    "S603": { type: "dot", x: 1596, y: 153, cn: "牛栏山站", en: "Niulanshan Rwy. Sta.", align: "left", offset: { x: 0, y: -3 }, textScale: { cn: 1, en: 1 } },
    "S604": { type: "dot", x: 1596, y: 117, cn: "怀柔站", en: "Huairou Rwy. Sta.", align: "left", offset: { x: 0, y: -2 }, textScale: { cn: 1, en: 1 } },
    "S605": { type: "dot", x: 1683, y: 100, cn: "密云北站", en: "Miyunbei Rwy. Sta.", align: "bottom", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 } },
    "S606": { type: "dot", x: 1596, y: 80, cn: "雁栖湖站", en: "Yanqihu Rwy. Sta.", align: "bottom", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 }, hideLabel: true },
    "S607": { type: "dot", x: 1639, y: 70, cn: "怀柔北站", en: "Huairoubei Rwy. Sta.", align: "bottom", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 }, hideLabel: true },
    "T101": { type: "dot", x: 1232, y: 1046, cn: "定海园", en: "Dinghaiyuan", align: "top", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 } },
    "T102": { type: "dot", x: 1199.9, y: 1046, cn: "定海园西", en: "Dinghaiyuanxi", align: "top", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 } },
    "T103": { type: "dot", x: 1167.2, y: 1046, cn: "经海一路", en: "Jinghai Yilu", align: "top", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 } },
    "T104": { type: "dot", x: 1124, y: 1046, cn: "亦创会展中心", en: "Yichuang Huizhan Zhongxin", align: "top", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 0.9 } },
    "T105": { type: "dot", x: 1083, y: 1064, cn: "荣昌东街", en: "Rongchang Dongjie", align: "top-right", offset: { x: 0, y: 8 }, textScale: { cn: 1, en: 1 }, hideLabel: true },
    "T106": { type: "dot", x: 1058, y: 1089, cn: "亦庄同仁", en: "Yizhuang Tongren", align: "left", offset: { x: 1, y: -6 }, textScale: { cn: 1, en: 1 } },
    "T107": { type: "dot", x: 1049, y: 1104, cn: "鹿圈东", en: "Lujuandong", align: "left", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 } },
    "T108": { type: "dot", x: 1049, y: 1117.5, cn: "泰河路", en: "Taihelu", align: "right", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 } },
    "T109": { type: "dot", x: 1049, y: 1131, cn: "九号村", en: "Jiuhaocun", align: "left", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 } },
    "T110": { type: "dot", x: 1049, y: 1144.5, cn: "四海庄", en: "Sihaizhuang", align: "right", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 } },
    "T111": { type: "dot", x: 1049, y: 1158, cn: "太和桥北", en: "Taiheqiaobei", align: "left", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 } },
    "T112": { type: "dot", x: 1049, y: 1171.5, cn: "瑞合庄", en: "Ruihezhuang", align: "right", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 } },
    "T113": { type: "dot", x: 1049, y: 1185, cn: "融兴街", en: "Rongxingjie", align: "left", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 } },
    "T114": { type: "dot", x: 1049, y: 1198.5, cn: "屈庄", en: "Quzhuang", align: "right", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 } },
    "T115": { type: "no", x: 1049, y: 1212, cn: "老观里", en: "Laoguanli", align: "left", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 } },
    "XJ01": { type: "dot", x: 289, y: 410, cn: "香山", en: "Fragrant Hills", align: "top", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 } },
    "XJ02": { type: "dot", x: 325, y: 417, cn: "国家植物园", en: "China National<br>Botanical Garden", align: "top-right", offset: { x: -6, y: 0 }, textScale: { cn: 1, en: 1 } },
    "XJ03": { type: "dot", x: 327, y: 445, cn: "万安", en: "Wan'an", align: "left", offset: { x: 0, y: -0.5 }, textScale: { cn: 1, en: 1 } },
    "XJ04": { type: "dot", x: 362, y: 460, cn: "茶棚", en: "Chapeng", align: "top", offset: { x: 0, y: -1 }, textScale: { cn: 1, en: 1 } },
    "XJ05": { type: "dot", x: 399, y: 460, cn: "颐和园西门", en: "Summer Palace<br>West Gate", align: "bottom", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 0.9 } },
    "XJ06": { type: "tsfo", x: 435, y: 460, cn: "巴沟", en: "Bagou", align: "bottom", offset: { x: 0, y: 0 }, textScale: { cn: 1, en: 1 }, hideLabel: true },
};
